### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by bilby-bot** [bilby-dev/bilby#294]
In GitLab by @git.ligo:gregory.ashton on Nov 8, 2018, 22:56

Eventually, it would be good if all "production" use of bilby happens using containers (i.e. docker/singularity). This will help make results reproducible, allow must users to skip the step of installing bilby[^1], and allow running of bilby outside of the LDG clusters, perhaps on the OSG or other computing resources.

Talking with @james\-clark I wrote out the following summary of the status and todo, I'll repeat it here so that others can join the conversion and help out. 

[^1]: Note that installing bilby is easy, but installing the samplers (multinest) can be tricky. Most peoples problems we see on the #help channel are installation related (i.e. different versions of python etc). 

## Current status

* bilby has docker images hosted on docker hub: https://hub.docker.com/r/bilbydev/bilby/tags/
* The tags refer to the pypi versions and are released by hand every time we do an update
* I've written a wiki page with pretty much all I know about docker: https://git.ligo.org/lscsoft/bilby/wikis/home (the point here is to say how *little* I know, not how much!)

## Todo

1. [ ] Understand if the docker images we've created can be used by singularity on the clusters. I'm pretty sure, but an expert opinion/advise would be greatly appreciated

2. [ ] Upload images to /cvmfs on the clusters. (if you where not aware already, this wiki page might be useful: https://wiki.ligo.org/Computing/DASWG/ContainersOnTheGrid, but I suspect you are as you've already uploaded bayeswave images!). Tom Downes helpfully pointed out that docker images can be hosted on the cluster so that they can be used by Conder (with the SingularityImage argument, but see point above). I've started this process, creating the images and pushing them (i.e. with

```bash
docker tag bilbydev/bilby containers.ligo.org/lscsoft/bilby:0.3.3
docker push containers.ligo.org/lscsoft/bilby:0.3.3
```

However, this is failing at the moment (if you look you won't see any bilby images). Tom Downes emailed me yesterday with this:

> Yes, you should expect to wait at least 30 minutes. But, you happen to be hitting this bug which I haven’t had time to look at:
>  
> https://github.com/sylabs/singularity/issues/1271
>  
> ESC[33mWARNING: Failed removing file: /cvmfs/ligo-containers.opensciencegrid.org/lscsoft/bilby/.digests/sha256/39/39857fdc19f59a3fd00e50da646b26b4a9fe5b0d2c798c8800ead8d89ed57850/opt/conda/lib/python3.6/site-packages/html5lib-1.0.1-py3.6.egg-info
> ESC[0mESC[91mERROR  : Error applying whiteout marker from docker layer.
> ESC[0mESC[31mABORT  : Retval = 255
 
> I’m hoping it will just go away once Singularity 3.0 gets packaged on Debian.
>  
> This usually shows up if you have a stage in your Dockerfile where it removes a previously-existing file in favor of a new one. You might be able to avoid that step without affecting the final product. You can test this by running
>  
> singularity build --sandbox /path/to/local/dir docker://containers.ligo.org/yourname/yourproject:yourtag
>  
> while logged into submit.ligo.uwm.edu.

I haven't yet understood the problem or how to fix it (or even debug it!) do you have any ideas?

3. [ ] Add automatic creation of images from master on push. Tom Downes suggested this, here is the relevant message where he explains how:

> Or you can do it using continuous integration on git.ligo.org. Here’s an example of how to push an image automatically within your repo:
>  
> https://git.ligo.org/lscsoft/lalsuite/blob/master/.gitlab-ci.yml#L185
>  
> The important bit is that your CI job needs to login with a special username and token that is automatically in the CI environment. I’m not sure how familiar you are with Docker, but there isn’t anything special to do the in Dockerfile, you just need to push the image -- one way or the other -- to containers.ligo.org.

Again, this would be super useful.

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:gregory.ashton on Feb 18, 2019, 01:18

Closing this issue as it is duplicated by #278

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:gregory.ashton on Feb 18, 2019, 01:18

closed

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:michael.williams on Oct 3, 2024, 17:56

unassigned @git.ligo:gregory.ashton
