### ISSUE TITLE
Stopping conditions to produce N independent samples

### ISSUE THREAD

**Issue by bilby-bot** [bilby-dev/bilby#352]
In GitLab by @git.ligo:christopher-berry on Feb 7, 2019, 17:03

Investigate how different samplers produce independent samples, so we can aim to produce a desired number of samples per run

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:christopher-berry on Feb 18, 2019, 22:41

**Stage 0**

* [ ]  Check whether each sampler returns independent samples or not
* [ ]  If not, find out how to generate independent samples
* [ ]  Implement decorrelating samples for each sampler
* [ ]  Document the above

**Stage 1**

* [ ]  Check stopping conditions for each sampler, and if it is possible to specify (or guestimate) effective samples
* [ ]  If not, implement (approximate) stopping conditions, for example by resubmitting until done
* [ ]  Create unit test which runs on toy likehood for each sampler
* [ ]  Document the above

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:christopher-berry on Feb 18, 2019, 22:46

@git.ligo:rhys.green for F2F discussions, perhaps you could address some Stage 0 tasks today?

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:colm.talbot on Jun 21, 2019, 02:34

See https://github.com/joshspeagle/dynesty/pull/135

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:gregory.ashton on Jun 25, 2019, 05:04

I'm moving this to the [feature requests wiki](https://git.ligo.org/lscsoft/bilby/wikis/feature_requests/) as a long-term issue.

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:gregory.ashton on Jun 25, 2019, 05:04

closed

**Comment by bilby-bot** [comment]
In GitLab by @git.ligo:michael.williams on Oct 3, 2024, 17:55

unassigned @git.ligo:christopher-berry
